### PR TITLE
Fixnode on old debian version

### PR DESCRIPTION
**Pull request by rtruxal**

### CODE REVIEW

**Comment by rtruxal** [comment]
Wooooo!!!!!!!!!! I actually managed to delete it!

**Comment by jenkstom** [comment]
Sorry, I'm not very good at github. I didn't notice this pull request. I added the package into the repository, which hopefully is the same fix you were trying to make. Although it doesn't look like there's anything here? I dunno, sorry. Let me know if there's anything you still need to change in case I screwed this all up.

**Comment by rtruxal** [comment]
Nooo I did the screwing up for sure! I tried to merge onto my `master` but accidentally did on yours.

Thanks for pushing a patch so quickly!!! I'll check today if it works & let you know.

Thanks again!
-RT

**Comment by jenkstom** [comment]
Ok. I don't really remember how to update this to the ansible galaxy. Guess I need to figure that out.

**Pull request closed without merging**
